default: &default
adapter: postgresql
encoding: unicode
host: localhost
username:
password:
pool: 5
production:
<<: *default
database: my_ap_production
test:
<<: *default
database: my_ap_test
development:
<<: *default
database: my_ap