# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e9f4428b778d7319254985625c645e097bc423aa4e26ba328bf9c534a38a8977f6d53df08f560955e5b00dd3269c9bc00c7f514a5d208dadf3c7db6e7064d09

test:
  secret_key_base: 531dc33608a4b5cb047f1bc0ecf8df8d5780fa602cc72d9e6c8d7aae1e0b97e112eb44211b168566258518cd86b66871cbd4b277c920769e954f0b15838b56b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
